name: Android Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Spotless Apply
        run: ./gradlew spotlessApply
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_PASSWORD: ${{ secrets.PASSWORD }}

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_PASSWORD: ${{ secrets.PASSWORD }}

      - name: Run Tests
        run: ./gradlew testDebugUnitTest
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_PASSWORD }}

      - name: Build Project
        run: ./gradlew assembleDebug
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_PASSWORD }}